name: adam
torch:
  lr: 0.01
  weight_decay: 0.0
init:
  name: random
maxepochs: 1000
lr_scheduler:
  factor: 1
  patience: 500
  threshold: 1e-5
  cooldown: 100
  min_lr: 1e-5
beta: 1e-7 #abs loss diff to terminate
patience: 5000